apiVersion: apps/v1
kind: Deployment
metadata:
  name: cape2e-controller-manager
  namespace: cape2e-system
  labels:
    control-plane: controller-manager
    cluster.x-k8s.io/provider: infrastructure-e2e
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
        cluster.x-k8s.io/provider: infrastructure-e2e
    spec:
      serviceAccountName: cape2e-controller-manager
      terminationGracePeriodSeconds: 10
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          args:
            - --leader-elect
          env:
            - name: E2E_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentialsSecretName }}
                  key: api-key
            - name: E2E_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentialsSecretName }}
                  key: auth-token
            - name: E2E_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentialsSecretName }}
                  key: project-id
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
            - containerPort: 8081
              name: health
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
