resources:
  - manager.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: e2enetworks/cluster-api-provider-e2e
    newName: e2enetworks/cluster-api-provider-e2e
    newTag: latest
