apiVersion: v2
name: cluster-api-provider-e2e
description: Cluster API Infrastructure Provider for E2E Networks
type: application
version: 0.2.1
appVersion: "0.2.1"
keywords:
  - cluster-api
  - e2e-networks
  - infrastructure-provider
home: https://github.com/e2enetworks/cluster-api-provider-e2e
sources:
  - https://github.com/e2enetworks/cluster-api-provider-e2e
annotations:
  cluster.x-k8s.io/provider: infrastructure-e2e
  cluster.x-k8s.io/version: v1.10.x
