//go:build !ignore_autogenerated

/*
Copyright 2024 E2E Networks Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	apiv1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
)

// DeepCopyInto is an autogenerated deepcopy function.
func (in *E2ECluster) DeepCopyInto(out *E2ECluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *E2ECluster) DeepCopy() *E2ECluster {
	if in == nil {
		return nil
	}
	out := new(E2ECluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *E2ECluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *E2EClusterList) DeepCopyInto(out *E2EClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]E2ECluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *E2EClusterList) DeepCopy() *E2EClusterList {
	if in == nil {
		return nil
	}
	out := new(E2EClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *E2EClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *E2EClusterSpec) DeepCopyInto(out *E2EClusterSpec) {
	*out = *in
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	out.Network = in.Network
	out.LoadBalancer = in.LoadBalancer
}

// DeepCopy is an autogenerated deepcopy function.
func (in *E2EClusterSpec) DeepCopy() *E2EClusterSpec {
	if in == nil {
		return nil
	}
	out := new(E2EClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *E2EClusterStatus) DeepCopyInto(out *E2EClusterStatus) {
	*out = *in
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(string)
		**out = **in
	}
	if in.FailureMessage != nil {
		in, out := &in.FailureMessage, &out.FailureMessage
		*out = new(string)
		**out = **in
	}
	out.Network = in.Network
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(apiv1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *E2EClusterStatus) DeepCopy() *E2EClusterStatus {
	if in == nil {
		return nil
	}
	out := new(E2EClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *E2ENetworkStatus) DeepCopyInto(out *E2ENetworkStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *E2ENetworkStatus) DeepCopy() *E2ENetworkStatus {
	if in == nil {
		return nil
	}
	out := new(E2ENetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *E2ENetwork) DeepCopyInto(out *E2ENetwork) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *E2ENetwork) DeepCopy() *E2ENetwork {
	if in == nil {
		return nil
	}
	out := new(E2ENetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *E2ELoadBalancer) DeepCopyInto(out *E2ELoadBalancer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *E2ELoadBalancer) DeepCopy() *E2ELoadBalancer {
	if in == nil {
		return nil
	}
	out := new(E2ELoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *E2EResourceReference) DeepCopyInto(out *E2EResourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *E2EResourceReference) DeepCopy() *E2EResourceReference {
	if in == nil {
		return nil
	}
	out := new(E2EResourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *E2EMachine) DeepCopyInto(out *E2EMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *E2EMachine) DeepCopy() *E2EMachine {
	if in == nil {
		return nil
	}
	out := new(E2EMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *E2EMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *E2EMachineList) DeepCopyInto(out *E2EMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]E2EMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *E2EMachineList) DeepCopy() *E2EMachineList {
	if in == nil {
		return nil
	}
	out := new(E2EMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *E2EMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *E2EMachineSpec) DeepCopyInto(out *E2EMachineSpec) {
	*out = *in
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(string)
		**out = **in
	}
	if in.SecurityGroupIDs != nil {
		in, out := &in.SecurityGroupIDs, &out.SecurityGroupIDs
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.EnablePublicIP != nil {
		in, out := &in.EnablePublicIP, &out.EnablePublicIP
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *E2EMachineSpec) DeepCopy() *E2EMachineSpec {
	if in == nil {
		return nil
	}
	out := new(E2EMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *E2EMachineStatus) DeepCopyInto(out *E2EMachineStatus) {
	*out = *in
	if in.InstanceID != nil {
		in, out := &in.InstanceID, &out.InstanceID
		*out = new(int)
		**out = **in
	}
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]apiv1beta1.MachineAddress, len(*in))
		copy(*out, *in)
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(string)
		**out = **in
	}
	if in.FailureMessage != nil {
		in, out := &in.FailureMessage, &out.FailureMessage
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(apiv1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *E2EMachineStatus) DeepCopy() *E2EMachineStatus {
	if in == nil {
		return nil
	}
	out := new(E2EMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *E2EClusterTemplate) DeepCopyInto(out *E2EClusterTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *E2EClusterTemplate) DeepCopy() *E2EClusterTemplate {
	if in == nil {
		return nil
	}
	out := new(E2EClusterTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *E2EClusterTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *E2EClusterTemplateList) DeepCopyInto(out *E2EClusterTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]E2EClusterTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *E2EClusterTemplateList) DeepCopy() *E2EClusterTemplateList {
	if in == nil {
		return nil
	}
	out := new(E2EClusterTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *E2EClusterTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *E2EClusterTemplateSpec) DeepCopyInto(out *E2EClusterTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *E2EClusterTemplateSpec) DeepCopy() *E2EClusterTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(E2EClusterTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *E2EClusterTemplateResource) DeepCopyInto(out *E2EClusterTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *E2EClusterTemplateResource) DeepCopy() *E2EClusterTemplateResource {
	if in == nil {
		return nil
	}
	out := new(E2EClusterTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *clusterv1ObjectMeta) DeepCopyInto(out *clusterv1ObjectMeta) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *clusterv1ObjectMeta) DeepCopy() *clusterv1ObjectMeta {
	if in == nil {
		return nil
	}
	out := new(clusterv1ObjectMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *E2EMachineTemplate) DeepCopyInto(out *E2EMachineTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *E2EMachineTemplate) DeepCopy() *E2EMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(E2EMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *E2EMachineTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *E2EMachineTemplateList) DeepCopyInto(out *E2EMachineTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]E2EMachineTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *E2EMachineTemplateList) DeepCopy() *E2EMachineTemplateList {
	if in == nil {
		return nil
	}
	out := new(E2EMachineTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *E2EMachineTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *E2EMachineTemplateSpec) DeepCopyInto(out *E2EMachineTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *E2EMachineTemplateSpec) DeepCopy() *E2EMachineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(E2EMachineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *E2EMachineTemplateResource) DeepCopyInto(out *E2EMachineTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *E2EMachineTemplateResource) DeepCopy() *E2EMachineTemplateResource {
	if in == nil {
		return nil
	}
	out := new(E2EMachineTemplateResource)
	in.DeepCopyInto(out)
	return out
}
